apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fleetman-cluster
  region: ap-southeast-1

nodeGroups:
  - name: fleetman-ng-1
    instanceType: t2.medium
    instanceName: fleetman-node-1
    volumeSize: 20
    desiredCapacity: 10
  - name: fleetman-ng-2
    instanceType: t2.medium
    instanceName: fleetman-node-2
    volumeSize: 20
    desiredCapacity: 5
